[package]
name = "roc-build"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
digest = "0.9"
meowhash = "0.3"
notify = "4"
sled = "0.34"
tempfile = "3.2"
walkdir = "2.3"
zerocopy = "0.5"
