on: [pull_request]

name: CI

env:
  RUST_BACKTRACE: 1

jobs:
  platform-specific:
    name: clippy, test --release

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    timeout-minutes: 90
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        with:
          clean: "true"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: download Roc nightly build
        if: startsWith(matrix.os, 'ubuntu')
        run: ./ci/download_latest_nightly.sh linux_x86_64

      - name: download Roc nightly build
        if: startsWith(matrix.os, 'macos')
        run: ./ci/download_latest_nightly.sh macos_x86_64

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

  platform-generic:
    name: cargo fmt, typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: "true"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: typos
        uses: crate-ci/typos@v1.0.4
